services:
  deeptrace-web:
    image: deeptrace:latest
    container_name: deeptrace-web
    network_mode: host
    environment:
      - DB_TYPE=dm8
      - DATABASE_URL=dm://SYSDBA:Dm8DtUlR16LY8h0uC01zSYx@218.202.229.156:7814
      - REDIS_HOST=localhost
      - REDIS_PORT=6397
      - REDIS_AUTH=Deeptrace@2025
      - NEXTAUTH_URL=http://192.168.30.131:3000
      - NEXTAUTH_SECRET=secret
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true
      - SALT=salt
      - LANGFUSE_WORKER_PASSWORD=mybasicauthsecret
      - ENCRYPTION_KEY=8f94183ebc9cd0702323781700473ec7778adf21c7faf9a25c9c19239d936974
      - LOG_LEVEL=info
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3000/api/public/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
