services:
  deeptrace-db:
    container_name: deeptrace-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=system
      - POSTGRES_PASSWORD=Deeptrace@2025
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./posegres_init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U system -d dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  deeptrace-redis:
    container_name: deeptrace-redis
    image: redis:7.2-alpine
    ports:
      - "6397:6379"
    command: redis-server --requirepass Deeptrace@2025
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  deeptrace-app:
    container_name: deeptrace-app
    image: compass/deeptrace:1.0.0
    ports:
      - "5000:5000"  # web 前端
      - "5001:5001"  # worker 后端
    environment:
      #  以下参数暂不生效
      # - LANGFUSE_INIT_ORG_ID=20250101
      # - LANGFUSE_INIT_ORG_NAME=orbitAI
      # - LANGFUSE_INIT_PROJECT_ID=20250101
      # - LANGFUSE_INIT_PROJECT_NAME=xinference
      # - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-8a79d84e-5537-47b7-86bb-ba36257684f2
      # - LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-d1d41a0b-672e-49c9-aece-f9a2b40828de
      # - LANGFUSE_INIT_USER_EMAIL=administrator@orbitai.com
      # - LANGFUSE_INIT_USER_NAME=administrator
      # - LANGFUSE_INIT_USER_PASSWORD=administrator

      # 数据库配置 - 指向 Docker 内的 PostgreSQL
      - DATABASE_URL=postgresql://system:Deeptrace%402025@deeptrace-db:5432/dev
      - DIRECT_URL=postgresql://system:Deeptrace%402025@deeptrace-db:5432/dev
      
      # Redis 配置 - 指向 Docker 内的 Redis
      - REDIS_HOST=deeptrace-redis
      - REDIS_PORT=6379
      - REDIS_AUTH=Deeptrace@2025
      
      # Next Auth 配置
      - NEXTAUTH_URL=http://192.168.10.177:5000
      - NEXTAUTH_SECRET=secret
      
      # Langfuse 配置
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true
      # 端口配置
      - PORT=5000
      - WORKER_PORT=5001
      
      # 安全配置
      - SALT=salt
      - LANGFUSE_WORKER_PASSWORD=mybasicauthsecret
      - ENCRYPTION_KEY=8f94183ebc9cd0702323781700473ec7778adf21c7faf9a25c9c19239d936974
      
      # 可选配置（留空）
      - EMAIL_FROM_ADDRESS=
      - SMTP_CONNECTION_URL=
      - S3_ENDPOINT=
      - S3_ACCESS_KEY_ID=
      - S3_SECRET_ACCESS_KEY=
      - S3_BUCKET_NAME=
      - S3_REGION=
    depends_on:
      deeptrace-db:
        condition: service_healthy
      deeptrace-redis:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        node worker/dist/index.js &
        node web/server.js
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: